version: '3.7'
services:
  db:
    container_name: db
    image: mariadb
    restart: unless-stopped
    ports:
      - 3306:3306
    networks:
      - development
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=dev
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=d3v123!23
      - MYSQL_ROOT_PASSWORD=d3v123!23
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    networks:
      - development
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
  php:
    build: .
    networks:
      - development
    volumes:
      - ./code:/code
networks:
  development:
volumes:
  db:
